with open('setup.py', 'r', encoding='utf-8') as f:
    content = f.read()

old = "    vbs_content = f''''\nGenerated by setup.exe"
new = "    vbs_content = f''''\n' Generated by setup.exe"

if old in content:
    content = content.replace(old, new)
    with open('setup.py', 'w', encoding='utf-8') as f:
        f.write(content)
    print('Fixed: Added comment marker to VBS header')
else:
    print('Pattern not found, checking alternatives...')
    # Try different patterns
    old2 = "    vbs_content = f''''\nGenerated"
    if old2 in content:
        print('Found partial pattern: old2')
    old3 = "vbs_content = f''''"
    if old3 in content:
        print('Found: vbs_content = f\\'\\'\\'\\'')
    # Show raw bytes around the pattern
    idx = content.find("vbs_content = f")
    if idx >= 0:
        print(f'Found at index {idx}')
        print(repr(content[idx:idx+80]))
